name: melon-ticket-bot
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:    
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.11.1
        with:
          product-id: 212838
          schedule-id: 100001
          seat-id: 10009
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: '<@here> 警报！10009区域有退票啦！快冲！'
